/**
 * Unit tests for the W#2 competition-storage pure helpers.
 *
 * Run with:
 *   node --test --experimental-strip-types src/lib/competition-storage-helpers.test.ts
 *
 * Same `node:test` + `node:assert/strict` pattern as the other pure-helper
 * tests in this folder. Helpers are pure (no Supabase / Next imports), so
 * the file loads without resolving any path-aliased modules.
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';

import {
  extensionFromMimeType,
  composeStoragePath,
  splitStoragePath,
  isAcceptedMime,
  findOrphans,
  ORPHAN_GRACE_MS,
  type StorageImageEntry,
} from './competition-storage-helpers.ts';
import { ACCEPTED_IMAGE_MIME_TYPES } from './shared-types/competition-scraping.ts';

/* ── extensionFromMimeType ──────────────────────────────────────────── */

test('extensionFromMimeType: image/jpeg → jpg', () => {
  assert.equal(extensionFromMimeType('image/jpeg'), 'jpg');
});

test('extensionFromMimeType: image/png → png', () => {
  assert.equal(extensionFromMimeType('image/png'), 'png');
});

test('extensionFromMimeType: image/webp → webp', () => {
  assert.equal(extensionFromMimeType('image/webp'), 'webp');
});

test('extensionFromMimeType: handles every accepted MIME type (exhaustiveness)', () => {
  // If a new MIME is added to ACCEPTED_IMAGE_MIME_TYPES without updating
  // the switch, this test will crash on the missing case at compile time
  // (TS exhaustive switch) — at runtime, missing branches return
  // undefined which fails the typeof check below.
  for (const mime of ACCEPTED_IMAGE_MIME_TYPES) {
    const ext = extensionFromMimeType(mime);
    assert.equal(typeof ext, 'string');
    assert.notEqual(ext.length, 0);
  }
});

/* ── composeStoragePath ──────────────────────────────────────────────── */

test('composeStoragePath: standard JPEG path', () => {
  assert.equal(
    composeStoragePath({
      projectId: 'p-1',
      competitorUrlId: 'cu-2',
      capturedImageId: 'ci-3',
      mimeType: 'image/jpeg',
    }),
    'p-1/cu-2/ci-3.jpg'
  );
});

test('composeStoragePath: PNG extension', () => {
  assert.equal(
    composeStoragePath({
      projectId: 'p-1',
      competitorUrlId: 'cu-2',
      capturedImageId: 'ci-3',
      mimeType: 'image/png',
    }),
    'p-1/cu-2/ci-3.png'
  );
});

test('composeStoragePath: WebP extension', () => {
  assert.equal(
    composeStoragePath({
      projectId: 'p-1',
      competitorUrlId: 'cu-2',
      capturedImageId: 'ci-3',
      mimeType: 'image/webp',
    }),
    'p-1/cu-2/ci-3.webp'
  );
});

test('composeStoragePath: UUID-shaped IDs survive intact', () => {
  const path = composeStoragePath({
    projectId: '550e8400-e29b-41d4-a716-446655440000',
    competitorUrlId: '550e8400-e29b-41d4-a716-446655440001',
    capturedImageId: '550e8400-e29b-41d4-a716-446655440002',
    mimeType: 'image/jpeg',
  });
  assert.equal(
    path,
    '550e8400-e29b-41d4-a716-446655440000/550e8400-e29b-41d4-a716-446655440001/550e8400-e29b-41d4-a716-446655440002.jpg'
  );
});

test('composeStoragePath: structure is exactly two slashes (folder/folder/file)', () => {
  // The wipeProjectImages walker depends on exactly two slashes per path.
  const path = composeStoragePath({
    projectId: 'p',
    competitorUrlId: 'c',
    capturedImageId: 'i',
    mimeType: 'image/png',
  });
  const slashCount = path.split('/').length - 1;
  assert.equal(slashCount, 2);
});

/* ── splitStoragePath ────────────────────────────────────────────────── */

test('splitStoragePath: standard path → (folder, filename)', () => {
  assert.deepEqual(splitStoragePath('p-1/cu-2/ci-3.jpg'), {
    folder: 'p-1/cu-2',
    filename: 'ci-3.jpg',
  });
});

test('splitStoragePath: filename only (no folder) → null', () => {
  // Defensive guard for malformed paths — every legitimate storage path
  // has at least the projectId/competitorUrlId/file structure.
  assert.equal(splitStoragePath('justafilename.jpg'), null);
});

test('splitStoragePath: empty string → null', () => {
  assert.equal(splitStoragePath(''), null);
});

test('splitStoragePath: trailing slash → empty filename', () => {
  // Garbage in / garbage out — caller is responsible for validating that
  // the storage path was generated by composeStoragePath.
  assert.deepEqual(splitStoragePath('p/'), {
    folder: 'p',
    filename: '',
  });
});

/* ── isAcceptedMime ──────────────────────────────────────────────────── */

test('isAcceptedMime: image/jpeg → true', () => {
  assert.equal(isAcceptedMime('image/jpeg'), true);
});

test('isAcceptedMime: image/png → true', () => {
  assert.equal(isAcceptedMime('image/png'), true);
});

test('isAcceptedMime: image/webp → true', () => {
  assert.equal(isAcceptedMime('image/webp'), true);
});

test('isAcceptedMime: image/svg+xml → false (XSS-rejected per §3)', () => {
  assert.equal(isAcceptedMime('image/svg+xml'), false);
});

test('isAcceptedMime: image/heic → false (browser-compat-rejected per §3)', () => {
  assert.equal(isAcceptedMime('image/heic'), false);
});

test('isAcceptedMime: video/mp4 → false', () => {
  assert.equal(isAcceptedMime('video/mp4'), false);
});

test('isAcceptedMime: null / undefined / number → false', () => {
  assert.equal(isAcceptedMime(null), false);
  assert.equal(isAcceptedMime(undefined), false);
  assert.equal(isAcceptedMime(42), false);
});

test('isAcceptedMime: empty string → false', () => {
  assert.equal(isAcceptedMime(''), false);
});

test('isAcceptedMime: case-sensitive (Image/JPEG → false)', () => {
  // Standard MIME-type matching is case-insensitive in HTTP spec, but we
  // require the canonical lowercase form so the storage path extension
  // table doesn't drift. requestUpload normalizes to lowercase before
  // calling this guard.
  assert.equal(isAcceptedMime('Image/JPEG'), false);
});

/* ── findOrphans (janitor) ───────────────────────────────────────────── */

// All findOrphans tests use a fixed `now` so the grace-window arithmetic
// is reproducible. Time travel via Date.parse on the entries' createdAt.
const NOW_MS = Date.parse('2026-05-08T12:00:00Z');

function entry(
  storagePath: string,
  createdAt: string | null
): StorageImageEntry {
  return { storagePath, createdAt };
}

test('findOrphans: empty input → empty output', () => {
  assert.deepEqual(findOrphans([], new Set(), NOW_MS), []);
});

test('findOrphans: file with matching DB row is NOT an orphan', () => {
  const entries = [entry('p/u/i.jpg', '2026-05-01T00:00:00Z')]; // a week old
  const known = new Set(['p/u/i.jpg']);
  assert.deepEqual(findOrphans(entries, known, NOW_MS), []);
});

test('findOrphans: file with no DB row AND older than 24h IS an orphan', () => {
  const entries = [entry('p/u/orphan.jpg', '2026-05-06T00:00:00Z')]; // ~60h old
  assert.deepEqual(findOrphans(entries, new Set(), NOW_MS), ['p/u/orphan.jpg']);
});

test('findOrphans: file with no DB row but younger than 24h is NOT an orphan (in-flight upload grace)', () => {
  // 1 hour old — still in grace window even without a DB row.
  const entries = [entry('p/u/inflight.jpg', '2026-05-08T11:00:00Z')];
  assert.deepEqual(findOrphans(entries, new Set(), NOW_MS), []);
});

test('findOrphans: file exactly at the grace boundary is NOT an orphan', () => {
  // created + graceMs === nowMs — boundary is inclusive (>= keeps it).
  const createdAt = new Date(NOW_MS - ORPHAN_GRACE_MS).toISOString();
  const entries = [entry('p/u/edge.jpg', createdAt)];
  assert.deepEqual(findOrphans(entries, new Set(), NOW_MS), []);
});

test('findOrphans: file just past the grace boundary IS an orphan', () => {
  // created + graceMs < nowMs by 1 ms.
  const createdAt = new Date(NOW_MS - ORPHAN_GRACE_MS - 1).toISOString();
  const entries = [entry('p/u/edge.jpg', createdAt)];
  assert.deepEqual(findOrphans(entries, new Set(), NOW_MS), ['p/u/edge.jpg']);
});

test('findOrphans: createdAt null → skipped (defensive, not an orphan)', () => {
  const entries = [entry('p/u/nodate.jpg', null)];
  assert.deepEqual(findOrphans(entries, new Set(), NOW_MS), []);
});

test('findOrphans: createdAt unparseable → skipped (defensive)', () => {
  const entries = [entry('p/u/garbage.jpg', 'not-a-date')];
  assert.deepEqual(findOrphans(entries, new Set(), NOW_MS), []);
});

test('findOrphans: mixes — keeps DB-matched, keeps in-grace, deletes old orphans', () => {
  const entries: StorageImageEntry[] = [
    entry('p/u/keep-known.jpg', '2026-05-01T00:00:00Z'),       // known
    entry('p/u/keep-fresh.jpg', '2026-05-08T11:30:00Z'),       // 30 min old
    entry('p/u/delete-old-1.jpg', '2026-05-06T00:00:00Z'),     // 60h old
    entry('p/u/delete-old-2.jpg', '2026-04-01T00:00:00Z'),     // a month old
    entry('p/u/skip-no-date.jpg', null),                        // null createdAt
  ];
  const known = new Set(['p/u/keep-known.jpg']);
  const orphans = findOrphans(entries, known, NOW_MS);
  assert.deepEqual(orphans.sort(), ['p/u/delete-old-1.jpg', 'p/u/delete-old-2.jpg']);
});

test('findOrphans: respects custom graceMs override', () => {
  // 2-hour grace; file is 90 min old → in grace.
  const entries = [entry('p/u/x.jpg', '2026-05-08T10:30:00Z')];
  assert.deepEqual(
    findOrphans(entries, new Set(), NOW_MS, 2 * 60 * 60 * 1000),
    []
  );
  // Same file, 1-hour grace → past it.
  assert.deepEqual(
    findOrphans(entries, new Set(), NOW_MS, 60 * 60 * 1000),
    ['p/u/x.jpg']
  );
});

test('findOrphans: ORPHAN_GRACE_MS is exactly 24 hours', () => {
  assert.equal(ORPHAN_GRACE_MS, 24 * 60 * 60 * 1000);
});
