/**
 * Unit tests for the W#2 competition-storage pure helpers.
 *
 * Run with:
 *   node --test --experimental-strip-types src/lib/competition-storage-helpers.test.ts
 *
 * Same `node:test` + `node:assert/strict` pattern as the other pure-helper
 * tests in this folder. Helpers are pure (no Supabase / Next imports), so
 * the file loads without resolving any path-aliased modules.
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';

import {
  extensionFromMimeType,
  composeStoragePath,
  splitStoragePath,
  isAcceptedMime,
} from './competition-storage-helpers.ts';
import { ACCEPTED_IMAGE_MIME_TYPES } from './shared-types/competition-scraping.ts';

/* ── extensionFromMimeType ──────────────────────────────────────────── */

test('extensionFromMimeType: image/jpeg → jpg', () => {
  assert.equal(extensionFromMimeType('image/jpeg'), 'jpg');
});

test('extensionFromMimeType: image/png → png', () => {
  assert.equal(extensionFromMimeType('image/png'), 'png');
});

test('extensionFromMimeType: image/webp → webp', () => {
  assert.equal(extensionFromMimeType('image/webp'), 'webp');
});

test('extensionFromMimeType: handles every accepted MIME type (exhaustiveness)', () => {
  // If a new MIME is added to ACCEPTED_IMAGE_MIME_TYPES without updating
  // the switch, this test will crash on the missing case at compile time
  // (TS exhaustive switch) — at runtime, missing branches return
  // undefined which fails the typeof check below.
  for (const mime of ACCEPTED_IMAGE_MIME_TYPES) {
    const ext = extensionFromMimeType(mime);
    assert.equal(typeof ext, 'string');
    assert.notEqual(ext.length, 0);
  }
});

/* ── composeStoragePath ──────────────────────────────────────────────── */

test('composeStoragePath: standard JPEG path', () => {
  assert.equal(
    composeStoragePath({
      projectId: 'p-1',
      competitorUrlId: 'cu-2',
      capturedImageId: 'ci-3',
      mimeType: 'image/jpeg',
    }),
    'p-1/cu-2/ci-3.jpg'
  );
});

test('composeStoragePath: PNG extension', () => {
  assert.equal(
    composeStoragePath({
      projectId: 'p-1',
      competitorUrlId: 'cu-2',
      capturedImageId: 'ci-3',
      mimeType: 'image/png',
    }),
    'p-1/cu-2/ci-3.png'
  );
});

test('composeStoragePath: WebP extension', () => {
  assert.equal(
    composeStoragePath({
      projectId: 'p-1',
      competitorUrlId: 'cu-2',
      capturedImageId: 'ci-3',
      mimeType: 'image/webp',
    }),
    'p-1/cu-2/ci-3.webp'
  );
});

test('composeStoragePath: UUID-shaped IDs survive intact', () => {
  const path = composeStoragePath({
    projectId: '550e8400-e29b-41d4-a716-446655440000',
    competitorUrlId: '550e8400-e29b-41d4-a716-446655440001',
    capturedImageId: '550e8400-e29b-41d4-a716-446655440002',
    mimeType: 'image/jpeg',
  });
  assert.equal(
    path,
    '550e8400-e29b-41d4-a716-446655440000/550e8400-e29b-41d4-a716-446655440001/550e8400-e29b-41d4-a716-446655440002.jpg'
  );
});

test('composeStoragePath: structure is exactly two slashes (folder/folder/file)', () => {
  // The wipeProjectImages walker depends on exactly two slashes per path.
  const path = composeStoragePath({
    projectId: 'p',
    competitorUrlId: 'c',
    capturedImageId: 'i',
    mimeType: 'image/png',
  });
  const slashCount = path.split('/').length - 1;
  assert.equal(slashCount, 2);
});

/* ── splitStoragePath ────────────────────────────────────────────────── */

test('splitStoragePath: standard path → (folder, filename)', () => {
  assert.deepEqual(splitStoragePath('p-1/cu-2/ci-3.jpg'), {
    folder: 'p-1/cu-2',
    filename: 'ci-3.jpg',
  });
});

test('splitStoragePath: filename only (no folder) → null', () => {
  // Defensive guard for malformed paths — every legitimate storage path
  // has at least the projectId/competitorUrlId/file structure.
  assert.equal(splitStoragePath('justafilename.jpg'), null);
});

test('splitStoragePath: empty string → null', () => {
  assert.equal(splitStoragePath(''), null);
});

test('splitStoragePath: trailing slash → empty filename', () => {
  // Garbage in / garbage out — caller is responsible for validating that
  // the storage path was generated by composeStoragePath.
  assert.deepEqual(splitStoragePath('p/'), {
    folder: 'p',
    filename: '',
  });
});

/* ── isAcceptedMime ──────────────────────────────────────────────────── */

test('isAcceptedMime: image/jpeg → true', () => {
  assert.equal(isAcceptedMime('image/jpeg'), true);
});

test('isAcceptedMime: image/png → true', () => {
  assert.equal(isAcceptedMime('image/png'), true);
});

test('isAcceptedMime: image/webp → true', () => {
  assert.equal(isAcceptedMime('image/webp'), true);
});

test('isAcceptedMime: image/svg+xml → false (XSS-rejected per §3)', () => {
  assert.equal(isAcceptedMime('image/svg+xml'), false);
});

test('isAcceptedMime: image/heic → false (browser-compat-rejected per §3)', () => {
  assert.equal(isAcceptedMime('image/heic'), false);
});

test('isAcceptedMime: video/mp4 → false', () => {
  assert.equal(isAcceptedMime('video/mp4'), false);
});

test('isAcceptedMime: null / undefined / number → false', () => {
  assert.equal(isAcceptedMime(null), false);
  assert.equal(isAcceptedMime(undefined), false);
  assert.equal(isAcceptedMime(42), false);
});

test('isAcceptedMime: empty string → false', () => {
  assert.equal(isAcceptedMime(''), false);
});

test('isAcceptedMime: case-sensitive (Image/JPEG → false)', () => {
  // Standard MIME-type matching is case-insensitive in HTTP spec, but we
  // require the canonical lowercase form so the storage path extension
  // table doesn't drift. requestUpload normalizes to lowercase before
  // calling this guard.
  assert.equal(isAcceptedMime('Image/JPEG'), false);
});
