'use client';

// W#2 P-49 Workstream 5 Fix Session D (2026-05-31) — read-only 3-column
// traceability table for the "Overall Analysis — Captured Reviews" box on
// the URL detail page. Per director's 2026-05-30 §1 addendum, the
// per-competitor bulleted AI output is rendered as Category / Complaint /
// source-reviews(+star count) instead of pasted free text.
//
// Design (director-confirmed at Fix Session D session start, all Recommended):
//   - Table on TOP; a free-text "Your notes" editor stays below it
//     (rendered by the sibling OverallAnalysisBox).
//   - READ-ONLY — the table is regenerated by re-running the AI; the notes
//     area below stays editable.
//   - Source column shows the FULL review text + star count for every
//     cited review.
//
// Back-compat: pre-v4 PER_PRODUCT rows stored only { summary } (free text).
// parseTraceabilityAnalysis returns null for those; we fall back to
// rendering the flattened summary text so legacy rows still display until
// the director re-runs the AI to get a structured row + table.

import { useMemo } from 'react';

import type { CapturedReview } from '@/lib/shared-types/competition-scraping';
import {
  parseTraceabilityAnalysis,
  buildTraceabilityRows,
  type TraceabilityReview,
} from '@/lib/competition-scraping/reviews-traceability';

export interface ReviewsTraceabilityTableProps {
  // Raw analysisJson from the latest PER_PRODUCT ReviewAnalysis row for this
  // URL (or null/undefined when no per-competitor run has happened yet).
  analysisJson: unknown;
  // The URL's captured reviews — used to resolve cited reviewIds to full
  // text + star counts for the source column.
  reviews: ReadonlyArray<CapturedReview>;
  testId?: string;
}

export function ReviewsTraceabilityTable({
  analysisJson,
  reviews,
  testId,
}: ReviewsTraceabilityTableProps) {
  const analysis = useMemo(
    () => parseTraceabilityAnalysis(analysisJson),
    [analysisJson]
  );

  const reviewsById = useMemo(() => {
    const m = new Map<string, TraceabilityReview>();
    for (const r of reviews) {
      m.set(r.id, { starRating: r.starRating, title: r.title, body: r.body });
    }
    return m;
  }, [reviews]);

  const rows = useMemo(
    () => (analysis ? buildTraceabilityRows(analysis, reviewsById) : []),
    [analysis, reviewsById]
  );

  // Legacy free-text fallback when there's no structured analysis.
  const legacySummary = useMemo(() => {
    if (analysis) return null;
    if (analysisJson && typeof analysisJson === 'object') {
      const s = (analysisJson as { summary?: unknown }).summary;
      if (typeof s === 'string' && s.trim()) return s;
    }
    return null;
  }, [analysis, analysisJson]);

  if (!analysis && !legacySummary) return null;

  return (
    <div style={boxStyle} data-testid={testId}>
      <div style={headerStyle}>Overall Analysis — Captured Reviews</div>
      {analysis ? (
        <div style={{ overflowX: 'auto' }}>
          <table style={tableStyle}>
            <thead>
              <tr>
                <th style={{ ...thStyle, width: '18%' }}>Category</th>
                <th style={{ ...thStyle, width: '34%' }}>Complaint</th>
                <th style={{ ...thStyle, width: '48%' }}>
                  Source reviews (with star count)
                </th>
              </tr>
            </thead>
            <tbody>
              {rows.map((row, i) => (
                <tr key={i}>
                  {row.categoryName !== null && (
                    <td
                      style={categoryCellStyle}
                      rowSpan={row.categoryRowSpan}
                    >
                      {row.categoryName}
                    </td>
                  )}
                  <td style={complaintCellStyle}>{row.bulletText}</td>
                  <td style={sourceCellStyle}>
                    {row.sources.length === 0 ? (
                      <span style={mutedStyle}>—</span>
                    ) : (
                      <ul style={sourceListStyle}>
                        {row.sources.map((s, j) => (
                          <li key={j} style={sourceItemStyle}>
                            <StarCount value={s.starRating} />
                            <span
                              style={s.missing ? mutedStyle : sourceTextStyle}
                            >
                              {s.text}
                            </span>
                          </li>
                        ))}
                      </ul>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      ) : (
        <div style={legacyTextStyle}>{legacySummary}</div>
      )}
    </div>
  );
}

function StarCount({ value }: { value: number | null }) {
  if (value == null) {
    return <span style={{ ...starWrapStyle, color: '#6e7681' }}>☆☆☆☆☆</span>;
  }
  return (
    <span
      style={starWrapStyle}
      aria-label={`${value} of 5 stars`}
      title={`${value} of 5 stars`}
    >
      {[1, 2, 3, 4, 5].map((n) => (
        <span key={n} style={{ color: n <= value ? '#f9c74f' : '#30363d' }}>
          {n <= value ? '★' : '☆'}
        </span>
      ))}
    </span>
  );
}

const boxStyle: React.CSSProperties = {
  marginTop: '16px',
  padding: '12px 14px',
  background: '#161b22',
  border: '1px solid #21262d',
  borderRadius: '8px',
};

const headerStyle: React.CSSProperties = {
  marginBottom: '10px',
  fontSize: '12px',
  color: '#8b949e',
  fontWeight: 600,
  textTransform: 'uppercase',
  letterSpacing: '0.04em',
};

const tableStyle: React.CSSProperties = {
  width: '100%',
  borderCollapse: 'collapse',
  fontSize: '13px',
  color: '#c9d1d9',
};

const thStyle: React.CSSProperties = {
  textAlign: 'left',
  verticalAlign: 'top',
  padding: '8px 10px',
  borderBottom: '1px solid #30363d',
  color: '#8b949e',
  fontWeight: 600,
  fontSize: '11px',
  textTransform: 'uppercase',
  letterSpacing: '0.03em',
};

const categoryCellStyle: React.CSSProperties = {
  verticalAlign: 'top',
  padding: '8px 10px',
  borderTop: '1px solid #30363d',
  borderRight: '1px solid #21262d',
  fontWeight: 600,
  color: '#e6edf3',
};

const complaintCellStyle: React.CSSProperties = {
  verticalAlign: 'top',
  padding: '8px 10px',
  borderTop: '1px solid #21262d',
  borderRight: '1px solid #21262d',
};

const sourceCellStyle: React.CSSProperties = {
  verticalAlign: 'top',
  padding: '8px 10px',
  borderTop: '1px solid #21262d',
};

const sourceListStyle: React.CSSProperties = {
  margin: 0,
  paddingLeft: 0,
  listStyle: 'none',
  display: 'flex',
  flexDirection: 'column',
  gap: '8px',
};

const sourceItemStyle: React.CSSProperties = {
  display: 'flex',
  flexDirection: 'column',
  gap: '2px',
};

const sourceTextStyle: React.CSSProperties = {
  whiteSpace: 'pre-wrap',
  color: '#c9d1d9',
};

const starWrapStyle: React.CSSProperties = {
  display: 'inline-flex',
  gap: '1px',
  fontSize: '13px',
  lineHeight: 1.4,
};

const mutedStyle: React.CSSProperties = {
  color: '#6e7681',
  fontStyle: 'italic',
  whiteSpace: 'pre-wrap',
};

const legacyTextStyle: React.CSSProperties = {
  whiteSpace: 'pre-wrap',
  fontSize: '13px',
  color: '#c9d1d9',
};
